version: '3.7'

services:
    db:
        container_name: q2-proyecto-design
        image: mariadb:latest
        restart: unless-stopped
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: 1234
        ports:
            - '3306:3306'
        volumes:
            - q2_proyecto_design_data:/var/lib/mysql

volumes:
    q2_proyecto_design_data:
